Add requirements-test.in
techservicesillinois/secops-splunk-null-router pull request #10
Opened 2022-06-01 20:17 UTC by mpitcel

2022-06-01 20:20 UTC, ddriddle submitted a review, later dismissed
Please remove vcrpy.

2022-06-01 20:22 UTC, baristaTam requested changes

2022-06-01 20:22 UTC, baristaTam commented on .gitignore
> +.requirements.venv
```suggestion
.requirements.venv

```

2022-06-01 20:22 UTC, baristaTam commented on Makefile
> +	rm -f requirements-test.txt
```suggestion
	rm -f requirements-test.txt
	
```

2022-06-01 20:22 UTC, baristaTam commented on .gitignore
> +.requirements.venv
missing eol

2022-06-02 16:01 UTC, gshere submitted a review, later dismissed

2022-06-02 16:02 UTC, spaldr approved these changes

2022-06-02 16:02 UTC, zdc217 approved these changes

2022-06-02 16:02 UTC, merged